# Generated by Django 5.1.6 on 2025-03-08 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'Аккаунт', 'verbose_name_plural': 'Доступные аккаунты'},
        ),
    ]
